

services:

  node:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - prom-server
      - loki
    volumes:
      - ./logs:/var/log/node-app # Node logs read by promtail

  prom-server:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus-config.yml:/etc/prometheus/prometheus.yml:ro

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    command:
      - "-config.file=/etc/loki/local-config.yaml"


  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3030:3000"
    depends_on:
      - prom-server
      - loki
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
  loki-data:
